import React from "react";
import { Header, Footer, Button } from "../../components/index";
import { Container, Product, Img, Figcaption, Flex, Price } from "./styles";
import exemple from "../../assets/imagem-ficticia.jpg";

const products = [
  {
    idProduct: 9,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 10,
    categoryIdCategory: 1,
    stock: 10,
    color: "Preto São Gabriel\n",
    finishingProcess: "Simples",
    cubaType: "embutida",
    description: "legal",
    imageLink: "pia-preto-simples-embutida",
    unitaryValue: 300.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 11,
    categoryIdCategory: 1,
    stock: 10,
    color: "Preto São Gabriel\n",
    finishingProcess: "Simples",
    cubaType: "embutida",
    description: "legal",
    imageLink: "pia-preto-simples-embutida",
    unitaryValue: 300.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 12,
    categoryIdCategory: 1,
    stock: 10,
    color: "Preto São Gabriel\n",
    finishingProcess: "Simples",
    cubaType: "embutida",
    description: "legal",
    imageLink: "pia-preto-simples-embutida",
    unitaryValue: 300.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 14,
    categoryIdCategory: 1,
    stock: 100,
    color: "travertino",
    finishingProcess: "reto",
    cubaType: "apoio",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 300.25,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 15,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 17,
    categoryIdCategory: 1,
    stock: 100,
    color: "travertino",
    finishingProcess: "reto",
    cubaType: "apoio",
    description: "muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 300.25,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 18,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 19,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 21,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 23,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 25,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 29,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox ",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 35,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "45",
    cubaType: "inox",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 36,
    categoryIdCategory: 1,
    stock: 15,
    color: "cinza ocre",
    finishingProcess: "simples",
    cubaType: "embutida",
    description: "legal muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 400.0,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 37,
    categoryIdCategory: 1,
    stock: 1550,
    color: "Travertino",
    finishingProcess: "reto",
    cubaType: "esculpida",
    description: "",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 469.25,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 38,
    categoryIdCategory: 1,
    stock: 1550,
    color: "Travertino",
    finishingProcess: "reto",
    cubaType: "esculpida",
    description: "",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 469.25,
    idCategory: 1,
    category: "Pia",
  },
  {
    idProduct: 41,
    categoryIdCategory: 1,
    stock: 100,
    color: "travertino",
    finishingProcess: "reto12",
    cubaType: "apoio12",
    description: "muito bom",
    imageLink: "pia-cinza-ocre-inox",
    unitaryValue: 864.25,
    idCategory: 1,
    category: "Pia",
  },
];

const handleProducts = ({ idProduct, color, description, unitaryValue }) => (
  <Product>
    <Img src={exemple} />
    <Figcaption>{color}</Figcaption>
    <Flex>
      <Price>R${unitaryValue}</Price>
      <Button>Comprar</Button>
    </Flex>
  </Product>
);

const Main = () => (
  <>
    <Header />
    <Container>{products.map(handleProducts)}</Container>
    <Footer />
  </>
);

export default Main;
