export { default as About } from './about-us'
export { default as Main } from './main'
export { default as Product } from './product'
export { default as Login } from './login'
export { default as Order } from './order'
